# Generated by Django 5.2.2 on 2025-06-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_author',
            field=models.CharField(default='Anonymous', max_length=20),
        ),
    ]
